# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netester.proto

import sys
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='netester.proto',
  package='netester',
  syntax='proto3',
  serialized_pb=_b('\n\x0enetester.proto\x12\x08netester\"\x10\n\x0eHandshakeHello\"\x0e\n\x0cHandshakeAck\"7\n\x0eSyncTimeReport\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\n\n\x02ts\x18\x02 \x01(\x04\x12\x0c\n\x04\x64iff\x18\x03 \x01(\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HANDSHAKEHELLO = _descriptor.Descriptor(
  name='HandshakeHello',
  full_name='netester.HandshakeHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=44,
)


_HANDSHAKEACK = _descriptor.Descriptor(
  name='HandshakeAck',
  full_name='netester.HandshakeAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=60,
)


_SYNCTIMEREPORT = _descriptor.Descriptor(
  name='SyncTimeReport',
  full_name='netester.SyncTimeReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='netester.SyncTimeReport.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts', full_name='netester.SyncTimeReport.ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff', full_name='netester.SyncTimeReport.diff', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['HandshakeHello'] = _HANDSHAKEHELLO
DESCRIPTOR.message_types_by_name['HandshakeAck'] = _HANDSHAKEACK
DESCRIPTOR.message_types_by_name['SyncTimeReport'] = _SYNCTIMEREPORT

HandshakeHello = _reflection.GeneratedProtocolMessageType('HandshakeHello', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKEHELLO,
  __module__ = 'netester_pb2'
  # @@protoc_insertion_point(class_scope:netester.HandshakeHello)
  ))
_sym_db.RegisterMessage(HandshakeHello)

HandshakeAck = _reflection.GeneratedProtocolMessageType('HandshakeAck', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKEACK,
  __module__ = 'netester_pb2'
  # @@protoc_insertion_point(class_scope:netester.HandshakeAck)
  ))
_sym_db.RegisterMessage(HandshakeAck)

SyncTimeReport = _reflection.GeneratedProtocolMessageType('SyncTimeReport', (_message.Message,), dict(
  DESCRIPTOR = _SYNCTIMEREPORT,
  __module__ = 'netester_pb2'
  # @@protoc_insertion_point(class_scope:netester.SyncTimeReport)
  ))
_sym_db.RegisterMessage(SyncTimeReport)


# @@protoc_insertion_point(module_scope)
